export { default as Main } from './Main'
export { default as Product } from './Product'
export { default as Story } from './Story'
export { default as Login } from './Login'
export { default as Register } from './Login'
export { default as Products } from './Products'
export { default as Checkout } from './Checkout'
